version: '2'
services:
  mancala-server:
    container_name: mancala-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/mancala-0.0.1-SNAPSHOT.jar
    image: mancala-server:0.0.1
    ports:
      - 8080:8080
    networks:
      - mancala-network
    environment:
      redis.host: redis-server
      redis.port: 6379
    restart: always
  redis-server:
    container_name: mancala-redis-server
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - mancala-network
    restart: always

networks:
  mancala-network:
    driver: bridge

volumes:
  redis-data: