version: '3'
services:
  mancala-server:
    container_name: mancala-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/mancala-0.0.1-SNAPSHOT.jar
    image: mancala-server:0.0.1
    ports:
      - 8080:8080
    networks:
      - mancala-network
    environment:
      redis.host: redis-server
      redis.port: 6379
      spring.session.store-type: redis
      spring.data.redis.host: redis-server
      spring.data.redis.port: 6379
    restart: always
    depends_on:
      - redis-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        labels: "com.docker.compose.logging.rotate-by=day"
  redis-server:
    container_name: mancala-redis-server
    command: redis-server --appendonly yes --replica-read-only no
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - mancala-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  mancala-network:
    driver: bridge

volumes:
  redis-data: